### ISSUE TITLE
feat: figure out fetching content from a modules repo

### ISSUE THREAD

**Issue by xynydev** [blue-build/website#3]

**Comment by gmpinder** [comment]
We could require module developers to create a `module.yml` file that defines inputs/yaml context and like a description. The defining valid fields would help with linting a user's recipe so that they know when they set something incorrectly.

**Comment by xynydev** [comment]
I agree, I also had this idea. This module metadata should include the description and name too, and the site would just be built automatically from a list of those files.

**Comment by xynydev** [comment]
I found this part in the Astro docs about fetching remote markdown: https://docs.astro.build/en/guides/markdown-content/#fetching-remote-markdown

It's possible, and I could make it happen like this:
```astro
// ExternalMarkdown.atro
---
const { src } = Astro.props
import { marked } from 'marked';
const response = await fetch(src);
const markdown = await response.text();
const content = marked.parse(markdown.split('\n').slice(1,-1).join('\n'));
---
<article set:html={content} />
<style>
    article pre code {
        white-space: pre-wrap;  
        word-wrap: break-word;
    }
</style>
```
```mdx
// rpm-ostree.mdx
---
title: rpm-ostree
description: A reference page in my new Starlight docs site.
---
import ExternalMarkdown from "@components/ExternalMarkdown.astro"

<ExternalMarkdown src="https://raw.githubusercontent.com/ublue-os/bling/main/modules/rpm-ostree/README.md"/>

```

There are a few problems, though
- The title generated with the Starlight frontmatter is shown first, then the title from the external markdown, which looks clumsy. I was able to remove the title from the external markdown with the split-slice-join hack, but wasn't able to remove Starlight's default title.
  - Starlight's frontmatter title doesn't support links, but that isn't a huge problem, as the link to the "topic" of the module can be added into the body text.
- Creating a totally custom page would make it impossible to leverage Starlight's template on that page.
- The text wrapping style actually doesn't apply for some reason and I cannot figure out why. 

The only/best possible solution I see for this is retiring module README.md's and either:
- Moving all module-related _documentation_ to the website, keeping at most an example configuration and configuration schema (the don't exist yet, but would be needed for a webui) in the module repo.
- Having a module.yml like gmpdiner suggested, with necessary content under different keys, `description`, `example-config`, etc. which would be individually ingested onto the website and built into docs pages.

**Comment by xynydev** [comment]
The WIP approach described above was commited in here: https://github.com/blue-build/website/commit/0ad58e46b0ad51ae3c67b860efa6fde6404e8200

I now think the `module.yml` approach is probably better for longevity and having docs where the code is (can be updated in the same pr, etc.). We should totally bring in the module pages with the only slightly broken, but already implemented WIP way.

**Comment by xynydev** [comment]
TODO: Make a plugin that takes links modules.json files as input and outputs module pages reference pages: https://starlight.astro.build/reference/plugins/. Look at https://github.com/HiDeoo/starlight-typedoc sourcecode for help.

**Comment by xynydev** [comment]
This is done now! Now just need to do & merge the changes into the module repo (bling currently).

I realize now that a `module.yml` wouldn't've been required here since I literally generate markdown files, but it allows for more longevity & programmatic reading of the reference pages I guess. For creating UIs or smth.
