### ISSUE TITLE
fix: Website light/dark mode requires page refresh to gather changed system light/dark mode

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/website#46]
Websites like GitHub gather system light/dark mode in real-time & automatically act accordingly.
BlueBuild website doesn't.

Video which shows what I mean:
https://github.com/blue-build/website/assets/65243233/6539d6ed-8b55-46bb-b1f5-ea9f386c40ad

**Comment by xynydev** [comment]
This should be possible with the following: https://stackoverflow.com/a/61349234

**Comment by xynydev** [comment]
Turns out this was [already included in Starlight](https://github.com/withastro/starlight/blob/76508f67a62a71456588dfc6a1b7135e4e0e985b/packages/starlight/components/ThemeSelect.astro#L61), but I'd never updated the framework before. I updated it, and now it works as expected.

**Comment by fiftydinar** [comment]
Can confirm it works
