### ISSUE TITLE
fix: `/community` page shows docs sidebar

### ISSUE THREAD

**Issue by CarrotManMatt** [blue-build/website#50]
Visiting https://blue-build.org/community shows the navigation-sidebar for the docs page, despite it not containing any of the sections under the "community" page.

![Screenshot_20240430-220227](https://github.com/blue-build/website/assets/108596565/835540b5-6a45-45e4-aa0d-190b60ff76a4)

**Comment by xynydev** [comment]
This is intentional to enable quicker navigation to other pages from the community page, and enable the hamburger menu on mobile devices, which also includes the top bar links. Close the issue if you agree with my assessment.
