### ISSUE TITLE
docs: recipe.yaml stages

### ISSUE THREAD

**Issue by ragibkl** [blue-build/website#56]
Looks like stages have been merged: https://github.com/blue-build/cli/pull/173

I even managed to use it: https://github.com/ragibkl/fedora-bluebuild/blob/08add5cc79c7aba0144f8daf8b0e7273c3347259/recipes/recipe.yml#L12-L18

Maybe add the docs to explain how to use it?

**Comment by gmpinder** [comment]
Yup we have a PR in progress for this here https://github.com/blue-build/website/pull/54

**Comment by ragibkl** [comment]
Oof! right, sorry I missed that! :pray:
